In [17]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
iris = pd.read_csv('D:/Letsupgrade/Naive Bayes/iris.csv',index_col=0)

In [19]:
iris.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

In [22]:
x=iris.iloc[:,:4].values
y=iris['Species'].values

In [27]:
# Splitting the dataset into the Training set and Test set

from sklearn.model_selection import train_test_split

In [28]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)

In [31]:
# Feature Scaling to bring the variable in a single scale

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)



In [34]:
# Fitting Naive Bayes Classification to the Training set with linear kernel

from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [36]:
# Predicting the Test set results

y_predict = gnb.predict(x_test)
print(y_predict)

['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa']


In [37]:
#lets see the actual and predicted value side by side

y_compare = np.vstack((y_test,y_predict)).T

#actual value on the left side and predicted value on the right hand side
y_compare[:5,:]

array([['Iris-versicolor', 'Iris-versicolor'],
       ['Iris-setosa', 'Iris-setosa'],
       ['Iris-virginica', 'Iris-virginica'],
       ['Iris-versicolor', 'Iris-versicolor'],
       ['Iris-versicolor', 'Iris-versicolor']], dtype=object)

In [38]:

# Making the Confusion Matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predict)
print(cm)

[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]


In [39]:
#finding accuracy from the confusion matrix.

a=cm.shape
CorrPred=0
falsePred=0

for row in range(a[0]):
    for c in range(a[1]):
        if row==c:
            CorrPred +=cm[row,c]
        else:
            falsePred +=cm[row,c]
print('Correct Prediction',CorrPred)
print('False Prediction',falsePred)
print('Accuracy of Naive Bayes',CorrPred/(cm.sum()))

Correct Prediction 38
False Prediction 0
Accuracy of Naive Bayes 1.0
