In [1]:
#Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

import numpy as np

a = np.array([2,4,6])
b = np.array([3,5,7])
print(a,b)

[2 4 6] [3 5 7]


In [3]:
print(np.greater(a,b))

[False False False]


In [5]:
print(np.greater_equal(a,b))

[False False False]


In [6]:
print(np.less(a,b))

[ True  True  True]


In [7]:
print(np.less_equal(a,b))

[ True  True  True]


In [9]:
#Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

c = np.zeros(10)
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
d = np.ones(10)
d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
e = np.ones(10)*5
e

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [16]:
#Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

f = np.array([[1,2,3],[4,5,6],[7,8,9]])
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
print(np.sum(f))

45


In [18]:
print(np.sum(f,axis=0))

[12 15 18]


In [19]:
print(np.sum(f,axis=1))

[ 6 15 24]


In [21]:
#Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

x  = np.array([100,150])
y  = np.array([25,50])
print(x,y)
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))

[100 150] [25 50]
[125 200]
[ 75 100]
[2500 7500]
[4. 3.]


In [25]:
#Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.

z = np.array([0,30,45,60,90])
z
print(np.sin(np.array(z) * np.pi/180))
print(np.cos(np.array(z) * np.pi/180))
print(np.tan(np.array(z) * np.pi/180))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
